<?php

declare (strict_types=1);

/**
 * @internal This class has been auto-generated by the Rade DI.
 */
class PrivateContainer extends Rade\DI\Container
{
    protected static array $privates;

    public array $parameters = [];

    protected array $methodsMap = [];

    protected array $types = [Psr\Container\ContainerInterface::class => ['container'], Rade\DI\AbstractContainer::class => ['container'], Rade\DI\Container::class => ['container']];

    protected array $aliases = [];

    public function __construct()
    {
        parent::__construct();
        self::$privates = [];
    }

    protected function getService1(): Rade\DI\Tests\Fixtures\Service
    {
        return self::$privates['service_1'] = new Rade\DI\Tests\Fixtures\Service();
    }

    protected function getService2(): Rade\DI\Tests\Fixtures\Service
    {
        return self::$privates['service_2'] = $this->resolver->resolve(Rade\DI\Tests\Fixtures\Service::class);
    }

    protected function getService3(): Rade\DI\Tests\Fixtures\Service
    {
        return new Rade\DI\Tests\Fixtures\Service();
    }
}
