<?php

declare (strict_types=1);

/**
 * @internal This class has been auto-generated by the Rade DI.
 */
class EmptyContainer extends Rade\DI\Container
{
    protected array $types = [
        Psr\Container\ContainerInterface::class => ['container'],
        Rade\DI\AbstractContainer::class => ['container'],
        Rade\DI\Container::class => ['container'],
        Rade\DI\ContainerInterface::class => ['container'],
    ];
}