<?php

declare (strict_types=1);

/**
 * @internal This class has been auto-generated by the Rade DI.
 */
class CompiledContainer extends Rade\DI\Container
{
    protected array $methodsMap = ['bar' => 'getBar', 'baz' => 'getBaz', 'foo' => 'getFoo', 'noxe' => 'getNoxe', 'recur' => 'getRecur'];

    protected array $types = [
        Psr\Container\ContainerInterface::class => ['container'],
        Rade\DI\AbstractContainer::class => ['container'],
        Rade\DI\Container::class => ['container'],
        Rade\DI\ContainerInterface::class => ['container'],
    ];

    protected function getBar()
    {
        return $this->services['bar'] = 345;
    }

    protected function getBaz()
    {
        return $this->services['baz'] = ['a' => 'b', 'c' => 'd'];
    }

    protected function getFoo()
    {
        return $this->services['foo'] = 'value';
    }

    protected function getNoxe(): Rade\DI\Tests\Fixtures\FooClass
    {
        return $this->services['noxe'] = new Rade\DI\Tests\Fixtures\FooClass();
    }

    protected function getRecur()
    {
        return $this->services['recur'] = ['a' => ['b' => ['hi' => 434.54], 'c' => 'd']];
    }
}